### ISSUE TITLE
Local files?

### ISSUE THREAD

**Issue by matelko64** [kartikk221/spotify-true-shuffle#2]
Hey, really like the service but is there a way it could work with local files? AFAIK it doesn't work with them and it's kind of a deal breaker for me :/

**Comment by kartikk221** [comment]
So the Spotify API does provide data about local songs but I think doesn't allow playback of it because local songs are usually restricted to certain devices and spotify can't always ensure playback. See this source code for more information: https://github.com/kartikk221/spotify-true-shuffle/blob/1af71f347482831db6767bd169904ce0870129e7/assets/js/main.js#L25
